version: "3.9"
services:
  torch-rw:
    image: "sachinx0e/torch-rw:1.2"
    container_name: "triple-walk"
    tty: true
    stdin_open: true
    ipc: host
    shm_size: 256m
    volumes: 
      - .:/root/workdir
      - ~/docker/triple_walk/.ssh:/root/.ssh
      - ~/docker/triple_walk/.vscode-server:/root/.vscode-server
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]